version: '3.9'

services:
# MongoDB
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

# Redis
  redis:
    build: redis
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - .cache:/data
    
# Golang API service
  golang:
    container_name: golang_container
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
      - redis

volumes:
  mongo_db: {}
