version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: on-failure
    volumes:
      - mongo_db:/data/db

  redis:
    build: ./redis/.
    container_name: redis_container_2
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - .cache:/data
    
  golang:
    container_name: golang_container_2
    build:
      dockerfile: Dockerfile.local
    environment:
      - PORT=${PORT}
      - STAGE=${STAGE}
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - redis
      - mongo_db
    # For Dockerfile.Local only
    volumes:
      - ./:/app

volumes:
  redis: {}
  mongo_db: {}