### Healt Check
GET http://localhost:8080

### Redirect Url
GET http://localhost:8080/AAAAFhm

### Create Short Url
POST http://localhost:8080/create-url
content-type: application/json

{
  "url": "https://facebook.com/"
}